name: Awesome readme lint
description: A GitHub Action that lint awesome readme in PR 
inputs:
  entry: 
    description: Entry file for parsing
    default: './README.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: check-circle
  color: green